### PR TITLE
Update README-CN.md

### PR DESCRIPTION
**Pull request by shengqiangzhang**

### CODE REVIEW

**Comment by yihong0618** [comment]
@shengqiangzhang why we need to change this!

**Comment by shengqiangzhang** [comment]
@yihong0618 

I can only access this page on my computer, not on other devices.
I added the parameter `-H 0.0.0.0` so that all devices can access the page.

**Comment by yihong0618** [comment]
@shengqiangzhang 
It is best to add this command to the optional?

**Comment by shengqiangzhang** [comment]
@yihong0618 
I agree, got it.

**Comment by yihong0618** [comment]
@shengqiangzhang  and please do not forget the English version README ~~~~

**Pull request closed without merging**
