### PR TITLE
new way to sync nrc

### PR DESCRIPTION
**Pull request by xiaolonggee**
(cherry picked from commit 06202c324b97e0407a0a871178ea150080a64c81)

### CODE REVIEW

**Review by ben-29 — APPROVED** [review]
LGTM

**Comment by yihong0618** [comment]
do not comments that lines for now, we will update the code later

**Comment by NaturezzZ** [comment]
I dont have a NRC test environment, but it looks like working.

**Review by NaturezzZ — APPROVED** [review]
I suppose it would work

**Pull request merged**
