### PR TITLE
style: use Tailwind CSS

### PR DESCRIPTION
**Pull request by tianheg**
Most of the work has been done, all that remains is to merge some module style files into className.

Suggestions for changes are welcome

Demo: https://running-page-fork-by-tianheg.vercel.app/

---

I found it difficult to merge conflicts, so create a new PR

### CODE REVIEW

**Comment by yihong0618** [comment]
error image
image

**Comment by tianheg** [comment]
The style is not right, I'm fixing it

**Comment by tianheg** [comment]
The style should be good now.

**Review by frostming — APPROVED** [review]
Thanks, both laptop and mobile look good to me.

This will make it much easier to bootstrap the project. Compiling the `sass` is such a pain.

**Comment by tianheg** [comment]
@yihong0618 The style should be good now.

**Review by yihong0618 — APPROVED** [review]
LGTM 
amazing work

**Pull request merged**
