### PR TITLE
show only running activities in garmin sync

### PR DESCRIPTION
**Pull request by liangch**

### CODE REVIEW

**Comment by yihong0618** [comment]
@liangch I test with my accout, but there is no data.
Besides, all my data is uploaded. Can you test this situation?

**Comment by liangch** [comment]
Have you put running activities under running category?  Do you see any activities from garmin connect with below links? 

https://connect.garmin.cn/modern/activities?activityType=running

https://connect.garmin.cn/proxy/activitylist-service/activities/search/activities?&activityType=running

I can see my data is there with activityType param.

**Comment by yihong0618** [comment]
@liangch 
not work for upload data

image

**Comment by liangch** [comment]
I am not sure the smooth way to handle the upload cases.  These categories (running/cycling/...) were there when I started to use the watch.

How about we keep this small change unmerged and see if there is any other user input?

WX20201112-152508@2x

**Comment by yihong0618** [comment]
@liangch maybe we can config it.

**Comment by yihong0618** [comment]
@liangch  I think will add config let the user choose or not will be better? And keep keep the old one default.

**Comment by yihong0618** [comment]
@liangch Can this pr be closed?

**Pull request closed without merging**
