### PR TITLE
feat: Typescript!

### PR DESCRIPTION
**Pull request by frostming**
Signed-off-by: Frost Ming <me@frostming.com>

This should be the first step. Let's consider the framework in the next.

Cross-link to #336

### CODE REVIEW

**Comment by shaonianche** [comment]
@frostming  Thinking of merging to the 2.0 branch and rewriting ..

**Comment by frostming** [comment]
> @frostming Thinking of merging to the 2.0 branch and rewriting ..

Sure, but it seems v2.0 branch is a bit outdated, can someone update it?

**Comment by yihong0618** [comment]
@frostming done 
@vlin @Mayandev can you help to review~?

**Comment by yihong0618** [comment]
merge first, let us v2.0 gogogo

**Pull request merged**
