### PR TITLE
style: dash-line(optional), opacity

### PR DESCRIPTION
**Pull request by ben-29**
#195 地图上虚线作为可选项

### CODE REVIEW

**Comment by ben-29** [comment]
add styling config in `src/utils/const.js`, default disable dash line
```javascript
// styling: set to `true` if you want dash-line route
const USE_DASH_LINE = true;
// styling: route line opacity: [0, 1]
const LINE_OPACITY = 0.4;
```

**Comment by yihong0618** [comment]
do we need set the `default`  false first?

**Review by yihong0618 — APPROVED** [review]
LGTM

**Comment by ben-29** [comment]
> do we need set the `default` false first?

Changed, make dash line style as default
Preview:
image

**Comment by yihong0618** [comment]
cool

**Comment by yihong0618** [comment]
merge first will give a test later.

**Comment by yihong0618** [comment]
@ben-29 

when a single I think we short use solid line
image

**Pull request merged**
