### PR TITLE
fix: Codoon tcx output use start_time as ID instead of Codoon id

### LINKED ISSUE #508: 咕咚导出的tcx数据导入高驰COROS网站会产生（时间）错误
经过对比是因为咕咚导出的tcx文件的ID是编号，而COROS默认的tcx数据格式里ID是起始时间（StartTime）

### PR DESCRIPTION
**Pull request by anChaOs**
fix #508

### CODE REVIEW

**Comment by yihong0618** [comment]
@anChaOs can you help fix the lint
pip install -U black 
black .

**Comment by anChaOs** [comment]
> @anChaOs can you help fix the lint pip install -U black black .

thx for message, I fixed the lint by black.

**Review by ben-29 — APPROVED** [review]
LGTM

Did you test if this patch fixed the import error with coros?

**Comment by anChaOs** [comment]
> LGTM
> 
> Did you test if this patch fixed the import error with coros?

Yes, this patch is useful for me.
I just uploaded my Codoon data onto Coros, it did fix start time error.

**Comment by yihong0618** [comment]
thanks

**Pull request merged**
