### PR TITLE
chore: upgrade node-sass to sass

### PR DESCRIPTION
**Pull request by tianheg**
reference: [sass/node-sass: Node.js bindings to libsass](https://github.com/sass/node-sass)

### CODE REVIEW

**Comment by yihong0618** [comment]
Thanks

**Comment by yihong0618** [comment]
@Mayandev can you take a look?

**Comment by Mayandev** [comment]
> @Mayandev can you take a look?

We can merge directly, the two packages have the same api, and the new package is fully upward compatible

**Comment by yihong0618** [comment]
> > @Mayandev can you take a look?
> 
> We can merge directly, the two packages have the same api, and the new package is fully upward compatible

Thanks.

**Pull request merged**
