### PR TITLE
Version change to Gatsby 4.0

### PR DESCRIPTION
**Pull request by irvingbennett**
I created a fork and only did changes to enable Gatsby 4.0 to run with Running_Page. Mostly, I deleted dependencies and installed them from scratch until I was able to get my local install to build and run. The changes were prompted because it was difficult to build a new site with the old requirements, mostly Gatsby 2.x and its dependencies.
As a side note, I was able to host running page on Vercel, Gatsby Cloud and Azure. The only inconvenience is that the running map is not showing on this builds, but it shows perfectly on my local install. I am sure that more eyes on this issue will fix it shortly.

### CODE REVIEW

**Comment by yihong0618** [comment]
Thanks will take a look later

**Comment by yihong0618** [comment]
Can you remove your data files like gpx

**Comment by irvingbennett** [comment]
Well, after adding the browser list change that shaonianche proposed, the page deployed on vercel doesn't show any errrors. It doesn't even show a map now. Curiously, it still works quite well on the localhost deployment. I wonder if the lack of gpx files on Github has anything to do with it.

**Comment by irvingbennett** [comment]
There is another change that I did which is not reflected on the github commits. I fixed the use of "/" division on all SASS calculations and instead used math.division(dividend, divisor). I did that using an npm script that applied the change to all the files that required it. In my builds I don't get any warnings about the use of "/" division in scss files: 
`<html>
<body>


DEPRECATION WARNING: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.
--
11:13:55.755 |  
11:13:55.756 | Recommendation: math.div(100%, 3) or calc(100% / 3)
11:13:55.756 |  
11:13:55.756 | More info and automated migrator: https://sass-lang.com/d/slash-div
11:13:55.756 |  
11:13:55.756 | ╷
11:13:55.756 | 73 │ .w-third { width: (100% / 3); }
11:13:55.756 | │                    ^^^^^^^^
11:13:55.757 | ╵
11:13:55.758 | node_modules/tachyons-sass/scss/_widths.scss 73:20  @import
11:13:55.759 | node_modules/tachyons-sass/tachyons.scss 72:10      @import
11:13:55.759 | src/styles/index.scss 3:9                           root stylesheet


</body>
</html>`

**Comment by yihong0618** [comment]
> Well, after adding the browser list change that shaonianche proposed, the page deployed on vercel doesn't show any errrors. It doesn't even show a map now. Curiously, it still works quite well on the localhost deployment. I wonder if the lack of gpx files on Github has anything to do with it.

@shaonianche

**Comment by yihong0618** [comment]
@irvingbennett 
We decided to merge this `PR` first then we will figure out how to solve this problem and make all `version` to latest

**Comment by yihong0618** [comment]
@irvingbennett Thank you very much

**Pull request merged**
